spring:
  application:
    name: stock-service

server:
  port: 9192

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:9009/eureka